version: "3.9"
services:
  gmail:
    image: orchestranexus/mcp-bridge:v0.0.0
    command: bash -c "sh /scripts/install_gmail.sh"
    privileged: true
    tty: true
    network_mode: host
    volumes:
      - ../../scripts:/scripts

